Add base implementation
21TORR/TaskManagerBundle pull request #2
Opened 2022-11-14 16:54 UTC by apfelbox

2022-11-14 21:05 UTC, keichinger requested changes

2022-11-14 21:05 UTC, keichinger commented on src/Exception/Mana/InvalidMessageTransportException.php
> +namespace Torr\TaskManager\Exception\Manager;
The namespace doesn't match the folder.

https://www.youtube.com/watch?v=01v9wALJ19w

Mana mana, dab diii, di di di.

2022-11-15 08:14 UTC, apfelbox commented on src/Exception/Mana/InvalidMessageTransportException.php
> +namespace Torr\TaskManager\Exception\Manager;
Why is that UI dialog in Phpstorm async? 🙄

2022-11-15 08:22 UTC, keichinger approved these changes

2022-11-15 08:22 UTC, merged